#!/bin/bash
cd "${0%/*}"

Size=$(cat SIZE)
Name=$(cat NAME)
Part=$(cat PARTITION)
FS=$(cat FS)
Extension=$(cat EXTENSION)
Path=$(cat PATH)

echo -e "\n(Size): $Size\n--------------------------------------------------------------\n(Name): $Name\n--------------------------------------------------------------\n(Partition Table): $Part\n--------------------------------------------------------------\n(File System): $FS\n--------------------------------------------------------------\n(Extension): $Extension\n--------------------------------------------------------------\n(Save Destination): $Path\n--------------------------------------------------------------\n" > CurrentSettings
